const itemData = [
    {
        id: "1ab",
        name: "짜장면",
        price: 6000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        category: "china",
        displayCate: "중식",
        img: "https://cdn.pixabay.com/photo/2017/07/27/16/45/i-2545938_1280.jpg",
    },
    {
        id: "2cd",
        name: "탕수육",
        price: 10000,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        category: "china",
        displayCate: "중식",
        img: "https://cdn.pixabay.com/photo/2018/04/26/08/01/food-3351333_1280.jpg",
    },
    {
        id: "3ef",
        name: "감자탕",
        price: 8000,
        category: "korea",
        displayCate: "한식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2018/09/10/09/21/haejangguk-3666599_1280.jpg",
    },
    {
        id: "4gh",
        name: "떡볶이",
        price: 5000,
        category: "korea",
        displayCate: "한식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2016/08/20/13/06/toppokki-1607479_1280.jpg",
    },
    {
        id: "5ab",
        name: "볶음면",
        price: 4500,
        category: "china",
        displayCate: "중식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2015/03/31/06/20/asia-700611_1280.jpg",
    },
    {
        id: "6cd",
        name: "오징어 구이",
        price: 10000,
        category: "korea",
        displayCate: "한식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2016/01/08/15/31/squid-1128410_1280.jpg",
    },
    {
        id: "7ef",
        name: "치킨",
        price: 90000,
        category: "usa",
        displayCate: "양식",

        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2015/03/11/00/31/chicken-667935_1280.jpg",
    },
    {
        id: "8gh",
        name: "피자",
        price: 14000,
        category: "usa",
        displayCate: "양식",

        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2020/06/08/16/49/pizza-5275191_1280.jpg",
    },
    {
        id: "9ab",
        name: "초밥",
        price: 12000,
        category: "japan",
        displayCate: "일식",

        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2016/04/26/03/55/salmon-1353598_1280.jpg",
    },
    {
        id: "10cd",
        name: "냉면",
        price: 9000,
        category: "korea",
        displayCate: "한식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2018/09/17/05/14/water-noodle-3683050_1280.jpg",
    },
    {
        id: "11ef",
        name: "라면",
        price: 4500,
        category: "korea",
        displayCate: "한식",
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2015/05/13/16/16/noodle-soup-765706_1280.jpg",
    },
    {
        id: "12bh",
        name: "아이스크림",
        price: 3000,
        category: "desert",
        displayCate: "후식",

        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2016/03/23/15/00/ice-cream-1274894_1280.jpg",
    },
    {
        id: "3oj",
        name: "스테이크",
        price: 20000,
        category: "usa",
        displayCate: "양식",

        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "https://cdn.pixabay.com/photo/2017/07/16/12/07/beef-2509104_1280.jpg",
    },
];
